package Frames.Cliente;

import Frames.Login.Login_Frame;
import Main.DbHandler;
import Modelos.Cuenta;
import Modelos.Movimiento;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/* Authors:
    José Carlos Paniagua Morales
    Aisler Moreno Pérez
    Juan Carlos Morales Jiménez
*/

public class Deposito extends javax.swing.JFrame {

    public DbHandler dbHandler = new DbHandler();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    
    public Deposito() {
        initComponents();
        this.setSize(420, 420);
        this.setLocationRelativeTo(null);
        this.setTitle("First Bank | Deposito");
        monto.setEnabled(false);
        btnDepositar.setEnabled(false);   
        cuentaDestino.setEnabled(false);

        try {
            if (dbHandler.existeCuentaBancaria(Login_Frame.cuentaConectada.getClienteId(), "CRC", "and estado='Activo'"))
                cuentas.addItem("CRC");
            if (dbHandler.existeCuentaBancaria(Login_Frame.cuentaConectada.getClienteId(), "USD", "and estado='Activo'"))
                cuentas.addItem("USD");
       
            cuentas.addActionListener((ActionEvent e) -> {
                if (!cuentas.getItemAt(cuentas.getSelectedIndex()).equals("Elegir cuenta")) {
                    labelSaldo.setText("Saldo actual: "+dbHandler.getSaldo(dbHandler.getCuentaId(Login_Frame.cuentaConectada.getClienteId(), cuentas.getItemAt(cuentas.getSelectedIndex()))));
                    monto.setEnabled(true);
                    btnDepositar.setEnabled(true);
                    cuentaDestino.setEnabled(true);
            }
                else {
                    labelSaldo.setText("Saldo actual: ");
                    monto.setEnabled(false);
                    btnDepositar.setEnabled(false); 
                    cuentaDestino.setEnabled(false);
            } 
        }); 
        } 
        catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error | Formato invalido");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnDepositar = new javax.swing.JButton();
        labelSaldo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cuentas = new javax.swing.JComboBox<>();
        monto = new javax.swing.JTextField();
        cuentaDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 420));
        setMinimumSize(new java.awt.Dimension(420, 420));
        setPreferredSize(new java.awt.Dimension(420, 420));
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDepositar.setBackground(new java.awt.Color(102, 102, 102));
        btnDepositar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDepositar.setForeground(new java.awt.Color(0, 255, 255));
        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 130, 60));

        labelSaldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSaldo.setForeground(new java.awt.Color(0, 102, 102));
        labelSaldo.setText("Saldo actual:");
        jPanel1.add(labelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Digite n°  de cuenta destinario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        cuentas.setBackground(new java.awt.Color(102, 102, 102));
        cuentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cuentas.setForeground(new java.awt.Color(0, 255, 255));
        cuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir cuenta" }));
        jPanel1.add(cuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 180, -1));

        monto.setBackground(new java.awt.Color(153, 153, 153));
        monto.setForeground(new java.awt.Color(0, 255, 255));
        monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoActionPerformed(evt);
            }
        });
        jPanel1.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 180, 30));

        cuentaDestino.setBackground(new java.awt.Color(153, 153, 153));
        cuentaDestino.setForeground(new java.awt.Color(0, 255, 255));
        cuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaDestinoActionPerformed(evt);
            }
        });
        jPanel1.add(cuentaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 180, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Digite Monto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 130, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FBIMG/Fondo1-Recuperado.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(420, 420));
        jLabel1.setMinimumSize(new java.awt.Dimension(420, 420));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(420, 420));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -40, 670, 730));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -100, 530, 550));

        btnSalir.setBackground(new java.awt.Color(0, 102, 102));
        btnSalir.setForeground(new java.awt.Color(153, 153, 153));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FBIMG/volver-flecha.jpg"))); // NOI18N
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir)
                .addContainerGap(378, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir)
                .addContainerGap(390, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        cuentas.setSelectedIndex(0);
        monto.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed

        try {
            if (monto.getText().isEmpty() || cuentas.getSelectedIndex()==0 || cuentaDestino.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Error | Rellene los campos");
        else if (!dbHandler.existeCuentaId(cuentaDestino.getText()))
            JOptionPane.showMessageDialog(null, "Error | La cuenta destino no existe");
        else if (!dbHandler.existeEstado(cuentaDestino.getText()))
            JOptionPane.showMessageDialog(null, "Error | La cuenta destino no existe");
        else if ((dbHandler.getSaldo(dbHandler.getCuentaId(Login_Frame.cuentaConectada.getClienteId(), cuentas.getItemAt(cuentas.getSelectedIndex()))) - Float.parseFloat(monto.getText())) < 0)
            JOptionPane.showMessageDialog(null, "Error | Cantidad no puede superar al saldo actual");
        else if (cuentaDestino.getText().equals(String.valueOf(dbHandler.getCuentaId(Login_Frame.cuentaConectada.getClienteId(), cuentas.getItemAt(cuentas.getSelectedIndex())))))
            JOptionPane.showMessageDialog(null, "Error | No puede depositar a la misma cuenta"); 
        else {
            Movimiento mov = new Movimiento(0, "0", "0", 0, 
                    dbHandler.getSaldo(dbHandler.getCuentaId(Login_Frame.cuentaConectada.getClienteId(), cuentas.getItemAt(cuentas.getSelectedIndex()))), 0);
            
            Cuenta cuentaActual = new Cuenta(0, 
                    dbHandler.getSaldo(dbHandler.getCuentaId(Login_Frame.cuentaConectada.getClienteId(), cuentas.getItemAt(cuentas.getSelectedIndex()))),
                    cuentas.getItemAt(cuentas.getSelectedIndex()), "Activo");
            
            float montoDivisa = Float.parseFloat(monto.getText());
            
            if (cuentas.getItemAt(cuentas.getSelectedIndex()).equals("CRC"))
                if (dbHandler.getMoneda(Integer.parseInt(cuentaDestino.getText())).equals("USD"))
                    montoDivisa = montoDivisa / dbHandler.getVentaUsd();
            if (cuentas.getItemAt(cuentas.getSelectedIndex()).equals("USD"))
                if (dbHandler.getMoneda(Integer.parseInt(cuentaDestino.getText())).equals("CRC"))
                    montoDivisa = Float.parseFloat(monto.getText()) * dbHandler.getVentaUsd(); 

            dbHandler.updateSaldo(cuentaActual.ejecutarDeposito(Float.parseFloat(monto.getText())), dbHandler.getCuentaId(Login_Frame.cuentaConectada.getClienteId(), cuentas.getItemAt(cuentas.getSelectedIndex())));
                    
            dbHandler.updateSaldo(dbHandler.getSaldo(Integer.parseInt(cuentaDestino.getText())) + montoDivisa, Integer.parseInt(cuentaDestino.getText()));
            
            //Se crea un movimiento en la cuenta origen
            dbHandler.insertMovimiento(formatoFecha.format(new Date()), "Deposito a cuenta "+cuentaDestino.getText(), Float.parseFloat(monto.getText()),
                (mov.getSaldoAnterior() - Float.parseFloat(monto.getText())),
                dbHandler.getCuentaId(Login_Frame.cuentaConectada.getClienteId(), cuentas.getItemAt(cuentas.getSelectedIndex())));
            
            //Se crea un movimiento en la cuenta destino
            dbHandler.insertMovimiento(formatoFecha.format(new Date()), 
                    "Llegada de dinero desde la cuenta "+dbHandler.getCuentaId(Login_Frame.cuentaConectada.getClienteId(), cuentas.getItemAt(cuentas.getSelectedIndex())), 
                    montoDivisa, dbHandler.getSaldo(Integer.parseInt(cuentaDestino.getText())), 
                    Integer.parseInt(cuentaDestino.getText()));
            
            labelSaldo.setText("Saldo actual: "+dbHandler.getSaldo(dbHandler.getCuentaId(Login_Frame.cuentaConectada.getClienteId(), cuentas.getItemAt(cuentas.getSelectedIndex()))));
            JOptionPane.showMessageDialog(null, "Deposito realizado con exito");
            }
            
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error | Formato invalido");
        }

    }//GEN-LAST:event_btnDepositarActionPerformed

    private void cuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaDestinoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
        MenuCliente ventanaCliente = new MenuCliente();
        ventanaCliente.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JTextField cuentaDestino;
    private javax.swing.JComboBox<String> cuentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JTextField monto;
    // End of variables declaration//GEN-END:variables
}
