package Frames.Cliente;

import Frames.Login.Login_Frame;
import Main.DbHandler;
import Modelos.Cuenta_Usuario;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/* Authors:
    José Carlos Paniagua Morales
    Aisler Moreno Pérez
    Juan Carlos Morales Jiménez
*/

public class CambioClave extends javax.swing.JFrame {

    /**
     * Creates new form estadocuenta
     */
    public CambioClave() {
        initComponents();
        this.setSize(440, 520);
        this.setLocationRelativeTo(null);
        this.setTitle("First Bank | Cambiar contraseña");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordAnterior = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        nuevaPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        confirmarNuevaPass = new javax.swing.JPasswordField();
        btnCambiar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("* La contraseña debe ser mayor a 8 pero menor a 16 caracteres");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("* La contraseña no acepta caracteres especiales");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Digite Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        passwordAnterior.setBackground(new java.awt.Color(153, 153, 153));
        passwordAnterior.setForeground(new java.awt.Color(0, 255, 255));
        passwordAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(passwordAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 200, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Digite Nueva Contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        nuevaPass.setBackground(new java.awt.Color(153, 153, 153));
        nuevaPass.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.add(nuevaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 200, 30));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Confirmar Nueva Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        confirmarNuevaPass.setBackground(new java.awt.Color(153, 153, 153));
        confirmarNuevaPass.setForeground(new java.awt.Color(0, 255, 255));
        confirmarNuevaPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarNuevaPassActionPerformed(evt);
            }
        });
        jPanel1.add(confirmarNuevaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 200, 30));

        btnCambiar.setBackground(new java.awt.Color(102, 102, 102));
        btnCambiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCambiar.setForeground(new java.awt.Color(0, 255, 255));
        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 90, 50));

        btnLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 100, 50));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FBIMG/volver-flecha.jpg"))); // NOI18N
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FBIMG/Fondo1-Recuperado.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -60, 590, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1411, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordAnteriorActionPerformed

    }//GEN-LAST:event_passwordAnteriorActionPerformed

    private void confirmarNuevaPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarNuevaPassActionPerformed

    }//GEN-LAST:event_confirmarNuevaPassActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        DbHandler dbHandler = new DbHandler();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        
        if (passwordAnterior.getText().isEmpty() || nuevaPass.getText().isEmpty() || confirmarNuevaPass.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Error | Campos obligatorios");
        else if (dbHandler.getPassword(Login_Frame.cuentaConectada.getUsuario()).equals(nuevaPass.getText()) || dbHandler.getPassword(Login_Frame.cuentaConectada.getUsuario()).equals(confirmarNuevaPass.getText()))
            JOptionPane.showMessageDialog(null, "Error | Nueva contraseña no puede ser igual a la anterior");
        else if (dbHandler.existePassword(passwordAnterior.getText()))
            if (nuevaPass.getText().equals(confirmarNuevaPass.getText())) {
                if ((Cuenta_Usuario.validarPassword(nuevaPass.getText()) && Cuenta_Usuario.validarPassword(confirmarNuevaPass.getText()))) {
                    dbHandler.updatePassword(Login_Frame.cuentaConectada.getUsuario(), nuevaPass.getText());
        
                    dbHandler.updateFechaModificacion(Login_Frame.cuentaConectada.getUsuario(), formatoFecha.format(new Date()));
                    
                    JOptionPane.showMessageDialog(null, "La clave se ha cambiado con éxito");
                    dispose();
                    Login_Frame ventanaLogin = new Login_Frame();
                    ventanaLogin.setVisible(true);
                }
            }
            else
                JOptionPane.showMessageDialog(null, "Error | Confirmar contraseña no coincide con nueva contraseña");
        else
            JOptionPane.showMessageDialog(null, "Error | Antigua contraseña no coincide con actual contraseña");
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        passwordAnterior.setText("");
        nuevaPass.setText("");
        confirmarNuevaPass.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
        MenuCliente ventanaCliente = new MenuCliente();
        ventanaCliente.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioClave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JPasswordField confirmarNuevaPass;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField nuevaPass;
    private javax.swing.JPasswordField passwordAnterior;
    // End of variables declaration//GEN-END:variables
}
