package Frames.Cliente;

import Frames.Login.Login_Frame;
import Main.DbHandler;
import Modelos.Cliente;
import Modelos.Movimiento;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/* Authors:
    José Carlos Paniagua Morales
    Aisler Moreno Pérez
    Juan Carlos Morales Jiménez
*/

public class EstadoCuenta extends javax.swing.JFrame {

    DbHandler dbHandler = new DbHandler();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    
    
    public EstadoCuenta() {
        initComponents();
        this.setSize(1020, 620);
        this.setLocationRelativeTo(null);
        this.setTitle("First Bank | Estados de cuenta");
                
        DefaultTableModel model = (DefaultTableModel) tablaCliente.getModel();
        btnListado.setEnabled(false);
        inputInicial.setEnabled(false);
        inputFinal.setEnabled(false);
        inputInicial.setDate(new Date());
        inputFinal.setDate(new Date());
        
        if (dbHandler.existeCuentaBancaria(Login_Frame.cuentaConectada.getClienteId(), "CRC", "and estado='Activo'"))
            cuentas.addItem("CRC");
        if (dbHandler.existeCuentaBancaria(Login_Frame.cuentaConectada.getClienteId(), "USD", "and estado='Activo'"))
            cuentas.addItem("USD");
        
        cuentas.addActionListener((ActionEvent e) -> {
            if (!cuentas.getItemAt(cuentas.getSelectedIndex()).equals("Elegir cuenta")) {
                btnListado.setEnabled(true);
                inputInicial.setEnabled(true);
                inputFinal.setEnabled(true);
                tablaCliente.removeAll();
                inputInicial.setDate(new Date());
                inputFinal.setDate(new Date());
                model.setRowCount(0);
            }
            else {
                btnListado.setEnabled(false);
                inputInicial.setEnabled(false);
                inputFinal.setEnabled(false);
                tablaCliente.removeAll();
                inputInicial.setDate(new Date());
                inputFinal.setDate(new Date());
                model.setRowCount(0);
            } 
        });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        btnListado = new javax.swing.JButton();
        cuentas = new javax.swing.JComboBox<>();
        inputFinal = new com.toedter.calendar.JDateChooser();
        inputInicial = new com.toedter.calendar.JDateChooser();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tablaCliente.setBackground(new java.awt.Color(102, 102, 102));
        tablaCliente.setForeground(new java.awt.Color(0, 255, 255));
        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N Cuenta", "Comprobante", "Mensaje", "Monto", "Saldo", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCliente.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tablaCliente);
        tablaCliente.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tablaCliente.getColumnModel().getColumnCount() > 0) {
            tablaCliente.getColumnModel().getColumn(0).setResizable(false);
            tablaCliente.getColumnModel().getColumn(1).setResizable(false);
            tablaCliente.getColumnModel().getColumn(2).setResizable(false);
            tablaCliente.getColumnModel().getColumn(2).setPreferredWidth(200);
            tablaCliente.getColumnModel().getColumn(3).setResizable(false);
            tablaCliente.getColumnModel().getColumn(4).setResizable(false);
            tablaCliente.getColumnModel().getColumn(5).setResizable(false);
        }

        btnListado.setBackground(new java.awt.Color(102, 102, 102));
        btnListado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListado.setForeground(new java.awt.Color(0, 255, 255));
        btnListado.setText("Generar listado");
        btnListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoActionPerformed(evt);
            }
        });

        cuentas.setBackground(new java.awt.Color(102, 102, 102));
        cuentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cuentas.setForeground(new java.awt.Color(0, 255, 255));
        cuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir cuenta" }));

        inputFinal.setBackground(new java.awt.Color(102, 102, 102));
        inputFinal.setForeground(new java.awt.Color(0, 255, 255));

        inputInicial.setBackground(new java.awt.Color(102, 102, 102));
        inputInicial.setForeground(new java.awt.Color(0, 255, 255));

        btnSalir.setBackground(new java.awt.Color(0, 102, 102));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FBIMG/volver-flecha.jpg"))); // NOI18N
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(inputInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuentas)
                    .addComponent(inputFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoActionPerformed
        if (cuentas.getItemAt(cuentas.getSelectedIndex()).equals("Elegir cuenta"))
            JOptionPane.showMessageDialog(null, "Error | Debe elegir cuenta");
        else
            try {
                if (Cliente.validarFecha(formatoFecha.format(inputInicial.getDate())) && Cliente.validarFecha(formatoFecha.format(inputFinal.getDate()))) {
                ArrayList<Movimiento> movimientos = dbHandler.getMovimientos(dbHandler.getCuentaId(Login_Frame.cuentaConectada.getClienteId(), cuentas.getItemAt(cuentas.getSelectedIndex())), 
                                                                            cuentas.getItemAt(cuentas.getSelectedIndex()), 
                                                                            formatoFecha.format(inputInicial.getDate()), formatoFecha.format(inputFinal.getDate()));
                
                DefaultTableModel model = (DefaultTableModel) tablaCliente.getModel();
                Object[] rows = new Object[6];

                for (int i = 0; i < movimientos.size(); i++) {
                    rows[0] = movimientos.get(i).getCuentaId();
                    rows[1] = movimientos.get(i).getMovimientoId();
                    rows[2] = movimientos.get(i).getFecha();
                    rows[3] = movimientos.get(i).getCantidad();
                    rows[4] = movimientos.get(i).getSaldoAnterior();  
                    rows[5] = movimientos.get(i).getMensaje();

                    model.addRow(rows);
                }
                
                btnListado.setEnabled(false);
            }
        }  
            catch (Exception err) {
                JOptionPane.showMessageDialog(null, "Error | Formato de fecha invalido");
        }
    }//GEN-LAST:event_btnListadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
        MenuCliente ventanaCliente = new MenuCliente();
        ventanaCliente.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadoCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListado;
    public javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cuentas;
    private com.toedter.calendar.JDateChooser inputFinal;
    private com.toedter.calendar.JDateChooser inputInicial;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tablaCliente;
    // End of variables declaration//GEN-END:variables
}
