package Frames.Cliente;

import Frames.Login.Login_Frame;
import Main.DbHandler;
import Modelos.Cuenta;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/* Authors:
    José Carlos Paniagua Morales
    Aisler Moreno Pérez
    Juan Carlos Morales Jiménez
*/

public class MenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form estadocuenta
     */
    public MenuCliente() {
        initComponents();
        this.setSize(620, 400);
        this.setLocationRelativeTo(null);
        this.setTitle("First Bank | Menu cliente");
        generarCuentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCuentas = new javax.swing.JTable();
        Deposito = new javax.swing.JButton();
        Retiro = new javax.swing.JButton();
        cambiarClave = new javax.swing.JButton();
        estadoDeCuenta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 639));
        setResizable(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCuentas.setBackground(new java.awt.Color(102, 102, 102));
        tablaCuentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tablaCuentas.setForeground(new java.awt.Color(0, 255, 255));
        tablaCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Cuentas", "Moneda", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCuentas.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(tablaCuentas);
        if (tablaCuentas.getColumnModel().getColumnCount() > 0) {
            tablaCuentas.getColumnModel().getColumn(0).setResizable(false);
            tablaCuentas.getColumnModel().getColumn(1).setResizable(false);
            tablaCuentas.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 510, 55));

        Deposito.setBackground(new java.awt.Color(102, 102, 102));
        Deposito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Deposito.setForeground(new java.awt.Color(0, 255, 255));
        Deposito.setText("Deposito");
        Deposito.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 102, 204), new java.awt.Color(255, 255, 255), null));
        Deposito.setDefaultCapable(false);
        Deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositoActionPerformed(evt);
            }
        });
        jPanel1.add(Deposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 200, 60));

        Retiro.setBackground(new java.awt.Color(102, 102, 102));
        Retiro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Retiro.setForeground(new java.awt.Color(0, 255, 255));
        Retiro.setText("Retiro");
        Retiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetiroActionPerformed(evt);
            }
        });
        jPanel1.add(Retiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 200, 60));

        cambiarClave.setBackground(new java.awt.Color(102, 102, 102));
        cambiarClave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cambiarClave.setForeground(new java.awt.Color(0, 255, 255));
        cambiarClave.setText("Cambiar Clave");
        cambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarClaveActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 200, 60));

        estadoDeCuenta.setBackground(new java.awt.Color(102, 102, 102));
        estadoDeCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        estadoDeCuenta.setForeground(new java.awt.Color(0, 255, 255));
        estadoDeCuenta.setText("Estado de Cuenta");
        estadoDeCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoDeCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(estadoDeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 200, 60));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 255, 255));
        jButton2.setText("Cerrar sesion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 10, 130, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FBIMG/Fondo1-Recuperado.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FBIMG/volver-flecha.jpg"))); // NOI18N
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1122, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1329, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2345, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(433, 433, 433))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estadoDeCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoDeCuentaActionPerformed
        EstadoCuenta estado = new EstadoCuenta();
        dispose();
        estado.setVisible(true);
    }//GEN-LAST:event_estadoDeCuentaActionPerformed

    private void cambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarClaveActionPerformed
        CambioClave clave = new CambioClave();
        dispose();
        clave.setVisible(true);
    }//GEN-LAST:event_cambiarClaveActionPerformed

    private void RetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetiroActionPerformed
        Retiro Ret = new Retiro();
        dispose();
        Ret.setVisible(true);
    }//GEN-LAST:event_RetiroActionPerformed

    private void DepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositoActionPerformed
        Deposito Dep = new Deposito();
        dispose();
        Dep.setVisible(true);
    }//GEN-LAST:event_DepositoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Login_Frame ventanaLogin = new Login_Frame();
        ventanaLogin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
        MenuCliente ventanaCliente = new MenuCliente();
        ventanaCliente.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    public static void generarCuentas() {
        try {
            DbHandler dbHandler = new DbHandler();
            
            ArrayList<Cuenta> listaCuentas = dbHandler.getCuentas(Login_Frame.cuentaConectada.getClienteId());

            DefaultTableModel model = (DefaultTableModel) tablaCuentas.getModel();
            Object[] rows = new Object[3];

            for (int i = 0; i < listaCuentas.size(); i++) {
                rows[0] = listaCuentas.get(i).getCuentaId();
                rows[1] = listaCuentas.get(i).getSaldo();
                rows[2] = listaCuentas.get(i).getMoneda();

                model.addRow(rows);
                
            }
        } 
        catch (Exception err) {}
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deposito;
    private javax.swing.JButton Retiro;
    public javax.swing.JButton btnSalir;
    private javax.swing.JButton cambiarClave;
    private javax.swing.JButton estadoDeCuenta;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable tablaCuentas;
    // End of variables declaration//GEN-END:variables
}
